apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sample-flux-example 
  labels: 
    name: "sample-flux-example"
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    #keel.sh/policy: major
    #keel.sh/trigger: poll
    #keel.sh/pollSchedule: "@every 30s"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sample-flux-example
  template:
    metadata:
      name: sample-flux-example
      labels:
        app: sample-flux-example
    spec:     
      containers:                    
        - image: {{ .Values.image.repository }}
          imagePullPolicy: Always # this is required to force pull image     
          name: sample-flux-example
          ports:
            - containerPort: 80
              #livenessProbe:
              # httpGet:
              #path: /
              #port: 8500
              #initialDelaySeconds: 10
              #timeoutSeconds: 5